version: '3'
services:
    elasticmq:
        image: softwaremill/elasticmq:latest
        ports:
            - "9324:9324"
        volumes:
            - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf
